In [7]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_boston

In [8]:
boston = load_boston()
df_boston = pd.DataFrame(data = boston.data, columns = boston.feature_names)
df_boston.shape

c:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.
    :func:`~sklearn.datasets.fetch_california_housing`) and the Ames housing
    dataset. You can load the datasets as follows::

        from sklearn.datasets import fetch_california_housing
        housing = fetch_california_housing()

    for the California housing dataset and::

        from sklearn.datasets import fetch_openml
        housing = fetch_openml(name="house_prices", as_frame=True)

    for the Ames housing dataset.
  warnings.warn(msg, category=FutureWarning)

(506, 13)

In [9]:
df_boston.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33

In [10]:
df_boston.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000

In [11]:
df_boston["Price"] = boston.target
df_boston

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,11.9

In [53]:
df_boston.shape

(506, 14)

In [12]:
df_boston.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  Price    506 non-null    float64
dtypes: float64(14)
memory usage: 55.5 KB

In [22]:
x_data = df_boston[['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT']]
y_data = df_boston['Price']

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train,y_test = train_test_split(x_data,y_data,test_size=0.2,random_state=0)
print(f"x train shape = {X_train.shape}")
print(f"x test shape = {X_test.shape}")
print(f"y train = {y_train.shape}")
print(f"y test = {y_test.shape}")

x train shape = (404, 13)
x test shape = (102, 13)
y train = (404,)
y test = (102,)

In [29]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

y_pred = regressor.score(X_train, y_train)
y_pred

0.7730135569264234

In [30]:
from sklearn.metrics import r2_score

r2_pred = regressor.predict(X_train)
r2_predic = r2_score(y_train,r2_pred)
r2_predic

0.7730135569264234

In [33]:
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()
df = pd.DataFrame(data=data.data, columns=data.feature_names)

In [36]:

df = df['mean area']

In [37]:
nump = df.to_numpy()

In [45]:
nump

array([1001. , 1326. , 1203. ,  386.1, 1297. ,  477.1, 1040. ,  577.9,
        519.8,  475.9,  797.8,  781. , 1123. ,  782.7,  578.3,  658.8,
        684.5,  798.8, 1260. ,  566.3,  520. ,  273.9,  704.4, 1404. ,
        904.6,  912.7,  644.8, 1094. ,  732.4,  955.1, 1088. ,  440.6,
        899.3, 1162. ,  807.2,  869.5,  633. ,  523.8,  698.8,  559.2,
        563. ,  371.1, 1104. ,  545.2,  531.5, 1076. ,  201.9,  534.6,
        449.3,  561. ,  427.9,  571.8,  437.6, 1033. ,  712.8,  409. ,
       1152. ,  656.9,  527.2,  224.5,  311.9,  221.8,  645.7,  260.9,
        499. ,  668.3,  269.4,  394.1,  250.5,  502.5, 1130. ,  244. ,
        929.4,  584.1,  470.9,  817.7,  559.2, 1006. , 1245. ,  506.3,
        401.5,  520. , 1878. , 1132. ,  443.3, 1075. ,  648.2, 1076. ,
        466.1,  651.9,  662.7,  728.2,  551.7,  555.1,  705.6, 1264. ,
        451.1,  294.5,  412.6,  642.5,  582.7,  143.5,  458.7,  298.3,
        336.1,  530.2,  412.5,  466.7, 1509. ,  396.5,  290.2,  480.4,
        629.9,  334.2,  230.9,  438.6,  245.2,  682.5,  782.6,  982. ,
        403.3, 1077. , 1761. ,  640.7,  553.5,  588.7,  572.6, 1138. ,
        674.5, 1192. ,  455.8,  748.9,  809.8,  761.7, 1075. ,  506.3,
        423.6,  399.8,  678.1,  384.8,  288.5,  813. ,  398. ,  512.2,
        355.3,  432.8,  432. ,  689.5,  640.1,  585. ,  519.4,  203.9,
        300.2,  381.9,  538.9,  460.3,  963.7,  880.2,  448.6,  366.8,
        419.8, 1157. , 1214. ,  464.5, 1686. ,  690.2,  357.6,  886.3,
        984.6,  685.9,  464.1,  565.4,  736.9,  372.7,  349.6,  227.2,
        302.4,  832.9,  526.4,  508.8, 2250. , 1311. ,  766.6,  402. ,
        710.6,  317.5, 1041. ,  420.3,  428.9,  463.7,  609.9,  507.4,
        288.1,  477.4,  671.4,  516.4,  588.9, 1024. , 1148. ,  642.7,
        461. ,  951.6, 1685. ,  597.8,  481.9,  716.6,  295.4,  904.3,
        529.4,  725.5, 1290. ,  428. , 2499. ,  948. ,  610.7,  578.9,
        432.2,  321.2, 1230. , 1223. ,  568.9,  561.3,  313.1,  761.3,
        546.4,  641.2,  329.6,  684.5,  496.4,  503.2,  895. ,  395.7,
        386.8, 1319. ,  279.6,  603.4, 1670. , 1306. ,  623.9,  920.6,
        575.3,  476.5,  389.4,  590. , 1155. ,  337.7,  541.6,  512.2,
        347. ,  406.3, 1364. ,  407.4, 1206. ,  928.2, 1169. ,  602.4,
       1207. ,  713.3,  773.5,  744.9, 1288. ,  933.1,  947.8,  758.6,
        928.3, 1419. ,  346.4,  561. ,  512.2,  344.9,  632.6,  388. ,
       1491. ,  289.9,  998.9,  435.6,  396.6, 1102. ,  572.3,  587.4,
       1138. ,  427.3, 1145. ,  805.1,  516.6,  489. ,  441. ,  515.9,
        394.1,  396. ,  651. ,  687.3,  513.7,  432.7,  492.1,  582.7,
        363.7,  431.1,  633.1,  334.2, 1217. ,  471.3, 1247. ,  334.3,
        403.1,  417.2,  537.3,  246.3,  566.2,  530.6,  418.7,  664.9,
        504.1,  409.1,  221.2,  481.6,  461.4, 1027. ,  244.5,  477.3,
        324.2, 1274. ,  504.8, 1264. ,  457.9,  489.9,  616.5,  446. ,
        813.7,  826.8,  793.2,  514. ,  387.3,  390. ,  464.4,  918.6,
        514.3, 1092. ,  310.8, 1747. ,  641.2,  280.5,  373.9, 1194. ,
        420.3,  321.6,  445.3,  668.7,  402.7,  426.7,  421. ,  758.6,
       2010. ,  716.6,  384.6,  485.8,  512. ,  593.7,  241. ,  278.6,
        491.9,  546.1,  496.6,  838.1,  552.4, 1293. , 1234. ,  458.4,
       1546. , 1482. ,  840.4,  711.8, 1386. , 1335. ,  579.1,  788.5,
        338.3,  562.1,  580.6,  361.6,  386.3,  372.7,  447.8,  462.9,
        541.8,  664.7,  462. ,  596.6,  392. , 1174. ,  321.6,  234.3,
        744.7, 1407. ,  446.2,  609.1,  558.1,  508.3,  378.2,  431.9,
        994. ,  442.7,  525.2,  507.6,  469.1,  370. ,  800. ,  514.5,
        991.7,  466.1,  399.8,  373.2,  268.8,  693.7,  719.5,  433.8,
        271.2,  803.1,  495. ,  380.3,  409.7,  656.1,  408.2,  575.3,
        289.7,  307.3,  333.6,  359.9,  381.1,  501.3,  685. ,  467.8,
       1250. , 1110. ,  673.7,  599.5,  509.2,  611.2,  592.6,  606.5,
        371.5,  928.8,  585.9,  340.9,  990. ,  441.3,  981.6,  674.8,
        659.7, 1384. ,  432. , 1191. ,  442.5,  644.2,  492.9,  557.2,
        415.1,  537.9,  520.2,  290.9,  930.9, 2501. ,  646.1,  412.7,
        537.3,  542.9,  536.9,  286.3,  980.5,  408.8,  289.1,  449.9,
        686.9,  465.4,  358.9,  506.9,  618.4,  599.4,  404.9,  815.8,
        455.3,  602.9,  546.3,  571.1,  747.2,  476.7,  666. , 1167. ,
        420.5,  857.6,  466.5,  992.1, 1007. ,  477.3,  538.7,  680.9,
        485.6,  480.1, 1068. , 1320. ,  689.4,  595.9,  476.3, 1682. ,
        248.7,  272.5,  453.1,  366.5,  819.8,  731.3,  426. ,  680.7,
        556.7,  658.8,  701.9,  391.2, 1052. , 1214. ,  493.1,  493.8,
        257.8, 1841. ,  388.1,  571. ,  293.2,  221.3,  551.1,  468.5,
        594.2,  445.2,  422.9,  416.2,  575.5, 1299. ,  365.6, 1308. ,
        629.8,  406.4,  178.8,  170.4,  402.9,  656.4,  668.6,  538.4,
        584.8,  573.2,  324.9,  320.8,  285.7,  361.6,  360.5,  378.4,
        507.9,  264. ,  514.3,  321.4,  311.7,  271.3,  657.1,  403.5,
        600.4,  386. ,  716.9, 1347. , 1479. , 1261. ,  858.1, 1265. ,
        181. ])

In [48]:
def binarySearch(array, x, low, high):
    while low <= high:
        mid = low+ (high-low)//2
        if array[mid]==x:
            return mid
        elif array[mid]< x:
            low = mid+ 1
        else :
            high = mid-1
    return -1

x = 807.2
sortNum = sorted(nump)
lensor = len(sortNum)
result = binarySearch(sortNum, x, 0, lensor-1)
if result !=-1:
    print(f"element found at index {result} with value ")
    
else:
    print("element not found")

element found at index 434 with value

In [52]:
import time
awal = time.time()
def linearSearch(array, n, x):
    for i in range(0,n):
        if(array[i]==x):
            return i
    return -1

x = 807.2
n = len(nump)
result = linearSearch(nump, n, x)
akhir = time.time()
if (result ==-1):
    print("element not found")
else:
    print(f"element found at index {result}")

print(f"waktu eksekusi = {awal-akhir}")

element found at index 434
waktu eksekusi = 0.0

In [55]:
df_nump = y_data.to_numpy()
df_nump_sorted = sorted(df_nump)
df_nump_sorted

[5.0,
 5.0,
 5.6,
 6.3,
 7.0,
 7.0,
 7.2,
 7.2,
 7.2,
 7.4,
 7.5,
 8.1,
 8.3,
 8.3,
 8.4,
 8.4,
 8.5,
 8.5,
 8.7,
 8.8,
 8.8,
 9.5,
 9.6,
 9.7,
 10.2,
 10.2,
 10.2,
 10.4,
 10.4,
 10.5,
 10.5,
 10.8,
 10.9,
 10.9,
 11.0,
 11.3,
 11.5,
 11.7,
 11.7,
 11.8,
 11.8,
 11.9,
 11.9,
 12.0,
 12.1,
 12.3,
 12.5,
 12.6,
 12.7,
 12.7,
 12.7,
 12.8,
 13.0,
 13.1,
 13.1,
 13.1,
 13.1,
 13.2,
 13.3,
 13.3,
 13.3,
 13.4,
 13.4,
 13.4,
 13.4,
 13.5,
 13.5,
 13.6,
 13.6,
 13.8,
 13.8,
 13.8,
 13.8,
 13.8,
 13.9,
 13.9,
 14.0,
 14.1,
 14.1,
 14.1,
 14.2,
 14.3,
 14.3,
 14.4,
 14.4,
 14.5,
 14.5,
 14.5,
 14.6,
 14.6,
 14.8,
 14.9,
 14.9,
 14.9,
 15.0,
 15.0,
 15.0,
 15.1,
 15.2,
 15.2,
 15.2,
 15.3,
 15.4,
 15.4,
 15.6,
 15.6,
 15.6,
 15.6,
 15.6,
 15.7,
 16.0,
 16.1,
 16.1,
 16.1,
 16.2,
 16.2,
 16.3,
 16.4,
 16.5,
 16.5,
 16.6,
 16.6,
 16.7,
 16.7,
 16.8,
 16.8,
 17.0,
 17.1,
 17.1,
 17.1,
 17.2,
 17.2,
 17.2,
 17.3,
 17.4,
 17.4,
 17.4,
 17.5,
 17.5,
 17.5,
 17.6,
 17.7,
 17.8,
 17.8,
 17.8,
 17.8,
 17.8,
 17.9,
 18.0,
 18.1,
 18.2,
 18.2,
 18.2,
 18.3,
 18.3,
 18.4,
 18.4,
 18.4,
 18.5,
 18.5,
 18.5,
 18.5,
 18.6,
 18.6,
 18.7,
 18.7,
 18.7,
 18.8,
 18.8,
 18.9,
 18.9,
 18.9,
 18.9,
 19.0,
 19.0,
 19.1,
 19.1,
 19.1,
 19.1,
 19.2,
 19.2,
 19.3,
 19.3,
 19.3,
 19.3,
 19.3,
 19.4,
 19.4,
 19.4,
 19.4,
 19.4,
 19.4,
 19.5,
 19.5,
 19.5,
 19.5,
 19.6,
 19.6,
 19.6,
 19.6,
 19.6,
 19.7,
 19.7,
 19.8,
 19.8,
 19.8,
 19.9,
 19.9,
 19.9,
 19.9,
 20.0,
 20.0,
 20.0,
 20.0,
 20.0,
 20.1,
 20.1,
 20.1,
 20.1,
 20.1,
 20.2,
 20.2,
 20.3,
 20.3,
 20.3,
 20.3,
 20.4,
 20.4,
 20.4,
 20.4,
 20.5,
 20.5,
 20.5,
 20.6,
 20.6,
 20.6,
 20.6,
 20.6,
 20.6,
 20.7,
 20.7,
 20.8,
 20.8,
 20.8,
 20.9,
 20.9,
 21.0,
 21.0,
 21.0,
 21.1,
 21.1,
 21.2,
 21.2,
 21.2,
 21.2,
 21.2,
 21.4,
 21.4,
 21.4,
 21.4,
 21.4,
 21.5,
 21.5,
 21.6,
 21.6,
 21.7,
 21.7,
 21.7,
 21.7,
 21.7,
 21.7,
 21.7,
 21.8,
 21.8,
 21.9,
 21.9,
 21.9,
 22.0,
 22.0,
 22.0,
 22.0,
 22.0,
 22.0,
 22.0,
 22.1,
 22.2,
 22.2,
 22.2,
 22.2,
 22.2,
 22.3,
 22.3,
 22.4,
 22.4,
 22.5,
 22.5,
 22.5,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.7,
 22.7,
 22.8,
 22.8,
 22.8,
 22.8,
 22.9,
 22.9,
 22.9,
 22.9,
 23.0,
 23.0,
 23.0,
 23.0,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.2,
 23.2,
 23.2,
 23.2,
 23.3,
 23.3,
 23.3,
 23.3,
 23.4,
 23.4,
 23.5,
 23.6,
 23.6,
 23.7,
 23.7,
 23.7,
 23.7,
 23.8,
 23.8,
 23.8,
 23.8,
 23.9,
 23.9,
 23.9,
 23.9,
 23.9,
 24.0,
 24.0,
 24.1,
 24.1,
 24.1,
 24.2,
 24.3,
 24.3,
 24.3,
 24.4,
 24.4,
 24.4,
 24.4,
 24.5,
 24.5,
 24.5,
 24.6,
 24.6,
 24.7,
 24.7,
 24.7,
 24.8,
 24.8,
 24.8,
 24.8,
 25.0,
 25.0,
 25.0,
 25.0,
 25.0,
 25.0,
 25.0,
 25.0,
 25.1,
 25.2,
 25.3,
 26.2,
 26.4,
 26.4,
 26.5,
 26.6,
 26.6,
 26.6,
 26.7,
 27.0,
 27.1,
 27.1,
 27.5,
 27.5,
 27.5,
 27.5,
 27.9,
 27.9,
 28.0,
 28.1,
 28.2,
 28.4,
 28.4,
 28.5,
 28.6,
 28.7,
 28.7,
 28.7,
 29.0,
 29.0,
 29.1,
 29.1,
 29.4,
 29.6,
 29.6,
 29.8,
 29.8,
 29.9,
 30.1,
 30.1,
 30.1,
 30.3,
 30.5,
 30.7,
 30.8,
 31.0,
 31.1,
 31.2,
 31.5,
 31.5,
 31.6,
 31.6,
 31.7,
 32.0,
 32.0,
 32.2,
 32.4,
 32.5,
 32.7,
 32.9,
 33.0,
 33.1,
 33.1,
 33.2,
 33.2,
 33.3,
 33.4,
 33.4,
 33.8,
 34.6,
 34.7,
 34.9,
 34.9,
 34.9,
 35.1,
 35.2,
 35.4,
 35.4,
 36.0,
 36.1,
 36.2,
 36.2,
 36.4,
 36.5,
 37.0,
 37.2,
 37.3,
 37.6,
 37.9,
 38.7,
 39.8,
 41.3,
 41.7,
 42.3,
 42.8,
 43.1,
 43.5,
 43.8,
 44.0,
 44.8,
 45.4,
 46.0,
 46.7,
 48.3,
 48.5,
 48.8,
 50.0,
 50.0,
 50.0,
 50.0,
 50.0,
 50.0,
 50.0,
 50.0,
 50.0,
 50.0,
 50.0,
 50.0,
 50.0,
 50.0,
 50.0,
 50.0]